---
- include: homesetup.yml
- include: avsetup.yml
- include: flatpak.yml
- include: oh-my-bash.yml
- include: macbook.yml
  when: ansible_facts['product_name'] is match("MacBookPro.*")
- name: Install Pinta
  package:
    name: pinta
    state: present
- name: Install Chromium (alt browser)
  package:
    name: chromium
    state: present
- name: Install rar utilities (firmware for Ender)
  package:
    name:
    - rar
    - unrar
    state: present
- name: Install barrier (shared keyboard/mouse)
  package:
    name:
    - barrier
    state: present
- name: Install audacious
  package:
    name: audacious
    state: present
- name: Civo CLI in profile
  lineinfile:
    path: /home/{{ managed_user }}/.bashrc
    regexp: '^alias civo=.*'
    line: alias civo="docker run -it --rm -v $HOME/.civo.json:/.civo.json civo/cli:latest"
    state: absent
  become: yes
  become_user: "{{ managed_user }}"
- name: Quick password gen
  package:
    name: pwgen
    state: present
- name: Discord for chat
  package:
    name: discord
    state: present
- name: tree for pretty directory tree in markdown
  package:
    name: tree
    state: present

