---
- include: flatpak.yml
- name: Install Pinta
  package:
    name: pinta
    state: present
- name: Install Chromium (alt browser)
  package:
    name: chromium
    state: present
- name: Install rar utilities (firmware for Ender)
  package:
    name:
    - rar
    - unrar
    state: present
- name: Install barrier (shared keyboard/mouse)
  package:
    name:
    - barrier
    state: present
