- name: Add {{ managed_user }} to dialout group for serial access
  user: 
    name: "{{ managed_user }}"
    group: "{{ managed_user }}"
    shell: "/bin/bash"
    groups: "dialout"
    append: yes
- name: Arduino IDE and utilities
  package:
    name: 
    - arduino
    - arduino-mk
    state: present
- name: Sanguino board definition - directory - for Ender Upgrade
  file:
    # Ansible should recursively create directories
    path: "/home/{{ managed_user }}/sketchbook/hardware"
    state: directory
  become: yes
  become_user: "{{ managed_user }}"
- name: Sanguino board definition - Git Checkout - for Ender Upgrade
  git:
    repo: https://github.com/Lauszus/Sanguino.git
    dest: /home/{{ managed_user }}/sketchbook/hardware/Sanguino
    version: master
  become: yes
  become_user: "{{ managed_user }}"