- name: Add {{ managed_user }} to dialout group for serial access
  user: 
    name: "{{ managed_user }}"
    group: "{{ managed_user }}"
    shell: "/bin/bash"
    groups: "dialout"
    append: yes
- name: Arduino IDE and utilities
  package:
    name: 
    - arduino
    - arduino-mk
    state: present
