# Adaopted from https://git-secret.io/ instructions
- name: Add apt-key for Git-Secret
  apt_key:
    url: https://api.bintray.com/users/sobolevn/keys/gpg/public.key
- name: Add Repository for Git-secret
  apt_repository:
    repo: deb https://dl.bintray.com/sobolevn/deb git-secret main
    state: present
- name: Install git-secret and gnupg
  package:
    name: 
      - git-secret
      - gpg
    state: present