- name: Install VSCode
  package:
    name: code
    state: present
- name: Install jq
  package:
    name: jq
    state: present
- name: Install xclip (Markdown paste extension)
  package:
    name: xclip
    state: present