- name: Install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.18.2/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0755
- name: Install Docker
  package:
    name: docker.io
    state: present
- name: Install kind
  get_url:
    url:  https://kind.sigs.k8s.io/dl/v0.8.0/kind-Linux-amd64
    dest: /usr/local/bin/kind
    mode: 0755
- name: Install k3d (stable)
  get_url:
#   Sticking with stable as it can cache images - don't want to pull down for EVERY cluster
    url:  https://github.com/rancher/k3d/releases/latest/download/k3d-linux-amd64
#    url: https://github.com/rancher/k3d/releases/download/v3.0.0-beta.1/k3d-linux-amd64
    dest: /usr/local/bin/k3d
    mode: 0755
- name: Add {{ managed_user }} to docker group
  user: 
    name: "{{ managed_user }}"
    group: "{{ managed_user }}"
    shell: "/bin/bash"
    groups: "docker"
    append: yes
  register: docker_group



#  uri:
#    # Gist with API exampels
#    url:  https://api.github.com/repos/jgm/pandoc/releases/latest
#    # See URI for other examples  https://docs.ansible.com/ansible/latest/modules/uri_module.html#uri-module
#    # JSON: https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#filters-for-formatting-data