- name: Install pip3
  package: 
    name:
      - python3
      - python3-pip 
    state: present
- name: Symlink for python executable
  file: 
    path: /usr/local/bin/python
    src: /usr/bin/python3
    state: link

  